### ISSUE TITLE
Docker install (Puppet) fails with missing Linux image

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_infra#35]
Currently the Vagrant provisioning fails at step `Docker Install`:

```
    default: ======================================================================
    default: Installing "docker"
    default: ======================================================================
    default: Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
    default: Notice: Downloading from https://forgeapi.puppet.com ...
    default: Notice: Installing -- do not interrupt ...
    default: /etc/puppetlabs/code/environments/production/modules
    default: └─┬ puppetlabs-docker (v1.0.4)
    default:   ├── puppetlabs-apt (v6.2.1)
    default:   ├── puppetlabs-stdlib (v5.1.0)
    default:   └── stahnma-epel (v1.3.1)
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 472]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 473]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 475]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 478]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Notice: Compiled catalog for dukecon-full.aschemann.intra in environment production in 0.40 seconds
    default: Notice: /Stage[main]/Docker::Repos/Package[debian-keyring]/ensure: created
    default: Notice: /Stage[main]/Docker::Repos/Package[debian-archive-keyring]/ensure: created
    default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
    default: Notice: /Stage[main]/Main/File[/data]/ensure: created
    default: Notice: /Stage[main]/Main/Exec[/bin/echo "This is a Vagrant Host"]/returns: executed successfully
    default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/content: content changed '{md5}b9de0ac9e2c9854b1bb213e362dc4e41' to '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
    default: Notice: /Stage[main]/Docker::Repos/Apt::Source[docker]/Apt::Key[Add key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 from Apt::Source docker]/Apt_key[Add key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 from Apt::Source docker]/ensure: created
    default: Notice: /Stage[main]/Docker::Repos/Apt::Source[docker]/Apt::Setting[list-docker]/File[/etc/apt/sources.list.d/docker.list]/ensure: defined content as '{md5}102b755a1d6bf9a41b84296a25ca1fb9'
    default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 event
    default: Notice: /Stage[main]/Docker::Repos/Package[cgroup-lite]/ensure: created
    default: Notice: /Stage[main]/Docker::Repos/Apt::Pin[docker]/Apt::Setting[pref-docker]/File[/etc/apt/preferences.d/docker.pref]/ensure: defined content as '{md5}ee2dbee1afbf071d58e0a88361de09f6'
    default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-4.15.0-20-generic' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E: Unable to locate package linux-image-extra-4.15.0-20-generic
    default: E: Couldn't find any package by glob 'linux-image-extra-4.15.0-20-generic'
    default: E: Couldn't find any package by regex 'linux-image-extra-4.15.0-20-generic'
    default: Error: /Stage[main]/Docker::Install/Package[linux-image-extra-4.15.0-20-generic]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-4.15.0-20-generic' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E: Unable to locate package linux-image-extra-4.15.0-20-generic
    default: E: Couldn't find any package by glob 'linux-image-extra-4.15.0-20-generic'
    default: E: Couldn't find any package by regex 'linux-image-extra-4.15.0-20-generic'
    default: Notice: /Stage[main]/Docker::Install/Package[docker]: Dependency Package[linux-image-extra-4.15.0-20-generic] has failures: true
    default: Warning: /Stage[main]/Docker::Install/Package[docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d/service-overrides.conf]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/Exec[docker-systemd-reload-before-service]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/default/docker-storage]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/default/docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/Service[docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/User[vagrant]: Skipping because of failed dependencies
    default: Error: Could not find a suitable provider for docker_network
    default: Notice: Applied catalog in 14.14 seconds

```

**Comment by ascheman** [comment]
This probably leads to a followup problem when installing Nexus:

```
    default: ======================================================================
    default: Installing "nexus"
    default: ======================================================================
    default: Loading Vagrant environment
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/image.pp", 38]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/image.pp", 40]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 472]:["/etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp", 113]
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/init.pp", 478]:["/etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp", 113]
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Integer. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp", 155]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function,
    default:                     with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp", 172]:
    default:    (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
    default: Notice: Compiled catalog for dukecon-full.aschemann.intra in environment production in 0.36 seconds
    default: Notice: /Stage[main]/Main/File[/data/nexus]/ensure: created
    default: Notice: /Stage[main]/Main/File[/data/nexus/sonatype]/ensure: created
    default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-4.15.0-20-generic' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E: Unable to locate package linux-image-extra-4.15.0-20-generic
    default: E: Couldn't find any package by glob 'linux-image-extra-4.15.0-20-generic'
    default: E: Couldn't find any package by regex 'linux-image-extra-4.15.0-20-generic'
    default: Error: /Stage[main]/Docker::Install/Package[linux-image-extra-4.15.0-20-generic]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-4.15.0-20-generic' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E: Unable to locate package linux-image-extra-4.15.0-20-generic
    default: E: Couldn't find any package by glob 'linux-image-extra-4.15.0-20-generic'
    default: E: Couldn't find any package by regex 'linux-image-extra-4.15.0-20-generic'
    default: Notice: /Stage[main]/Docker::Install/Package[docker]: Dependency Package[linux-image-extra-4.15.0-20-generic] has failures: true
    default: Warning: /Stage[main]/Docker::Install/Package[docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d/service-overrides.conf]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/Exec[docker-systemd-reload-before-service]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/default/docker-storage]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/File[/etc/default/docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Service/Service[docker]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/Docker::Image[sonatype/nexus:2.14.11-01]/File[/usr/local/bin/update_docker_image.sh]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/Docker::Image[sonatype/nexus:2.14.11-01]/Exec[/usr/local/bin/update_docker_image.sh sonatype/nexus:2.14.11-01]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/Docker::Run[nexus]/File[/etc/systemd/system/docker-nexus.service]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/Docker::Run[nexus]/Exec[docker-nexus-systemd-reload]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/Docker::Run[nexus]/Service[docker-nexus]: Skipping because of failed dependencies
    default: Notice: Applied catalog in 0.69 seconds
    default: Sleeping 60s until Docker/Nexus is up and running
    default: 1..1
    default: Error GETing http://localhost:8081/nexus/: Can't connect to localhost:8081 (Connection refused) at /vagrant/modules/nexus/scripts/test.pl line 13.
    default: # Looks like your test exited with 111 before it could output anything.
```

**Comment by autoit4you** [comment]
Looks like it's trying to pull in an old version of puppetlabs-docker which doesn't support Ubuntu 18.04.

**Comment by ascheman** [comment]
Can you fix/update the version? We had to pin some versions in the past due to version dependency mismatches (Puppet is a mess here). So you might need to be careful about version changes of required Puppet modules. Probably you could also try to fork/fix the puppetlabs-docker module?

**Comment by ascheman** [comment]
Unfortunately the build now fails with

```
    default: ======================================================================
    default: Installing "dukecon"
    default: ======================================================================
    default: Notice: Compiled catalog for dukecon-full.aschemann.intra in environment production in 0.21 seconds
    default: Notice: /Stage[main]/Main/Package[postgresql-client-common]/ensure: created
    default: Error: Command exceeded timeout
    default: Error: /Stage[main]/Docker::Compose/Exec[Install Docker Compose 1.18.0]/returns: change from 'notrun' to ['0'] failed: Command exceeded timeout
    default: Notice: /Stage[main]/Docker::Compose/File[/usr/bin/docker-compose-1.18.0]: Dependency Exec[Install Docker Compose 1.18.0] has failures: true
    default: Warning: /Stage[main]/Docker::Compose/File[/usr/bin/docker-compose-1.18.0]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Docker::Compose/File[/usr/bin/docker-compose]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/etc/docker-compose]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/postgresql]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/postgresql/data]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/postgresql/backup]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/server]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/server/config]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/server/cache]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/server/heapdumps]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/server/logs]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/feedback]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/feedback/config]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/feedback/cache]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/feedback/heapdumps]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/data/dukecon/testing/feedback/logs]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[/etc/docker-compose/dukecon-testing]: Skipping because of failed dependencies
    default: Warning: /Stage[main]/Main/File[create docker-compose/dukecon-testing]: Skipping because of failed dependencies
    default: Notice: /Stage[main]/Main/File[/etc/cron.daily/backup-dukecon-postgres-testing]: Dependency Docker_compose[/etc/docker-compose/dukecon-testing/docker-compose.yml] has failures: true
    default: Warning: /Stage[main]/Main/File[/etc/cron.daily/backup-dukecon-postgres-testing]: Skipping because of failed dependencies
    default: Error: Could not find a suitable provider for docker_compose
    default: Notice: Applied catalog in 303.84 seconds
    default: ======================================================================
    default: Installing "jenkins-native"
    default: ======================================================================
    default: Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
    default: Notice: Downloading from https://forgeapi.puppet.com ...
    default: Error: Unparsable version range: "'>=1.7.0'"
    default: Error: Try 'puppet help module install' for usage
```
